Added Msn Emojis (Windows Live Messenger)
lambtron/emojipacks pull request #67
Opened 2016-10-14 12:10 UTC by tahaipek

Added Msn Emojis. (Windows Live Messenger) 

- Be right back 
- Cigarette 
- High 5 
- Xbox 
- Turtle 
- Crossed fingers 
- Age, sex, location 
- Handcuffs 
- Smile 
- Grin 
- Suprised 
- Tongue smile 
- Wink 
- Sad 
- Confused 
- Disappointed 
- Crying 
- Shy 
- Cool 
- Angry 
- Angel 
- Devil 
- Don't tell 
- Teeth 
- Dull 
- Sarcastic 
- Telling secrets 
- Sick 
- Don't know 
- Thinking 
- Party 
- Rolling eyes 
- Drowsy 
- Coffee 
- Thumb up 
- Thumb down 
- Beer 
- Cocktail 
- Girl 
- Guy 
- Guy hug 
- Girl hug 
- Bat 
- Cake 
- Heart 
- Broken heart 
- Kiss 
- Present 
- Rose 
- Wilted rose 
- Camera 
- Film 
- Cat 
- Dog 
- Phone 
- Lightbulb 
- Music note 
- Sleeping moon 
- Star 
- Envelope 
- Clock 
- MSN Messenger icon 
- Snail 
- Black sheep 
- Plate 
- Pizza 
- Soccer 
- Car 
- Airplane 
- Umbrella 
- Island with palm tree 
- Computer 
- Mobile phone 
- Storm 
- Lightning 
- Money

2017-02-05 18:29 UTC, hugovk commented on packs/msn.yaml
> +    name: msnıslandwithpalmtree
> Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: msnıslandwithpalmtree

https://travis-ci.org/hugovk/emojipacks/builds/198613178#L964

That `ı` should be an `i`.

2017-02-05 18:29 UTC, hugovk requested changes

2017-02-05 18:29 UTC, hugovk commented on packs/msn.yaml
> +    name: msnıslandwithpalmtree
> Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: msnıslandwithpalmtree

https://travis-ci.org/hugovk/emojipacks/builds/198613178#L964

That `ı` should be an `i`.

2017-03-04 23:28 UTC, zachfeldman commented
@tahaipek if you can make the changes @hugovk suggested, I will merge this!

2017-03-17 23:25 UTC, zachfeldman commented
Hey there @tahaipek  , I'm closing this PR for now but feel free to open it back up later on if you'd like if it's still relevant!

2017-03-17 23:25 UTC, closed without merging