Fixes broken links in skype.yaml
lambtron/emojipacks pull request #85
Opened 2017-02-16 17:45 UTC by peteratticusberg

also adds more skype emoticons

source: http://www.skaip.org/skype-emoticons

2017-02-16 20:49 UTC, hugovk requested changes
@peteratticusberg A lot of these images are too big to upload to Slack, and a few are badly named.

I suggest removing those which are too big, and renaming those with invalid names.

```
Found 128 errors in packs/skype.yaml
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ancientone.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/angel.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/anger.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/red.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/target.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/auld.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/bandit.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/beer.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/bhangra.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: :-$
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/bomb.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/bug.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/busyday.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/cake.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/unsee.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/cat.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/cheese.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/shivering.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/computer.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/golmaal.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: 8=
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: ;-
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/cwl.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: \:d/
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/dance.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/discodancer.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/disgust.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/doctorstrange.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/donkey.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/dream.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: |-
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ring.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: >:
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/facepalm.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/festiveparty.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/finger.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ghost.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/learn.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: =ǝe=
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/happy.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/hearteyes.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/hi.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/hug.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/hungrycat.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/idea.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ill.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/inlove.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/bollylove.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/island.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/wasntme.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/kaecilius.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/karlmordo.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/lfcfacepalm.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/lfclaugh.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/lfcparty.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ladyvampire.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/lang.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: :-d
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/laugh.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/listening.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/headphones.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/makeup.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/mariachilove.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/mmm.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/monkeygiggle.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/hungover.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/movember.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/muscle.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/muscleman.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: :-x
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/neil.gif
Error: custom emoji names can only contain lower case letters, numbers, dashes and underscores: b|
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/ontheloo.gif
Error: must be smaller than 64K in file size: http://static.skaip.org/img/emoticons/v2/ffffff/party.gif
Error: must be sma [...]

2017-02-27 02:58 UTC, peteratticusberg commented
@hugovk very fair point, fired this off in haste 😢 . Fixed the issues per your comment.

2017-02-27 07:18 UTC, hugovk requested changes

2017-02-27 07:18 UTC, hugovk commented on packs/skype.yaml
> +- name: b|
`|` is not allowed, custom emoji names can only contain lower case letters, numbers, dashes and underscores.

2017-02-27 07:18 UTC, hugovk commented on packs/skype.yaml
> +- name: b|
`|` is not allowed, custom emoji names can only contain lower case letters, numbers, dashes and underscores.

2017-03-04 20:57 UTC, zachfeldman commented
@peteratticusberg if you fix the above I'll probably merge this!

2017-03-17 23:24 UTC, zachfeldman commented
Hey there @peteratticusberg , I'm closing this PR for now but feel free to open it back up later on if you'd like if it's still relevant!

2017-03-17 23:24 UTC, closed without merging